package com.mono.controller;

import java.security.Principal;
import java.util.Optional;

import org.springframework.http.HttpStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.mono.payload.UserRequest;
import com.mono.payload.UserResponse;
import com.mono.repo.UserRepository;
import com.mono.service.IUserService;
import com.mono.util.JwtUtil;
import com.mono.entity.User;

@RestController
@RequestMapping("/api/user")
public class UserRestController {

	@Autowired
	private IUserService userService;
	
	@Autowired
	private UserRepository userRepository;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Autowired
	private JwtUtil jwtUtil;
	
	@PostMapping("/save")
	public ResponseEntity<String> createUser(
			@RequestBody User user
			) throws Exception 
	{
		User isEmailExist = userRepository.findByUsername(user.getUsername());
		if(isEmailExist == null)
			throw new Exception("Email is already used with another account");
		
		Integer id = userService.saveUser(user);
		return ResponseEntity.ok("User Created : " + id);
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request) 
	{
		//This code Reads un,pwd from client and tries to validate by checking
		// using userdetails service for token generation
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						request.getUsername(), request.getPassword()
						)
				);
		
		String token1 = jwtUtil.generateToken(request.getUsername());
		return ResponseEntity.ok(new UserResponse(token1, "Generated By Mr. RAGHU"));
	}
	
	
	@PostMapping("/welcome")
	public ResponseEntity<String> showUserData(Principal principal) {
		System.out.println("principal:-"+principal);
		System.out.println("====:"+principal.getClass().getName());
		return ResponseEntity.ok("Hello : " + principal.getName());
	}
	
	@GetMapping("/profile")
	public ResponseEntity<User> findUserByJwtToken(@RequestHeader("Authorization") String jwt) throws Exception{
		User user = userService.findUserByJwtToken(jwt);
		return new ResponseEntity<User>(user,HttpStatus.OK);
	}
	
}
